// Placeholder generated by CLI. Public API lives in ./core, ./registry,
// ./render, ./expression, and ./adapter (see ../public-api.ts). This file
// is removed when Phase 1 implementation begins.
export {};
